### PR TITLE
fix LM import

### PR DESCRIPTION
**Pull request by jebeck**
I was trying to use umap-js in a Webpack-bundled application and getting this:

```
Uncaught (in promise) TypeError: LM is not a function
    at findABParams (8c9806fb-0bfd-4ab7-934e-7686db05bb0f:14861)
    at UMAP.initializeOptimization (8c9806fb-0bfd-4ab7-934e-7686db05bb0f:14641)
    at UMAP.initializeFit (8c9806fb-0bfd-4ab7-934e-7686db05bb0f:14323)
    at UMAP.<anonymous> (8c9806fb-0bfd-4ab7-934e-7686db05bb0f:14285)
```

Dug into the node_modules and looks like the problem is that `ml-levenberg-marquardt` only has a default export, and so the `import * as...`-style import does not work. Changing the `import * as LM from 'ml-levenberg-marquardt';` to `import LM from 'ml-levenberg-marquardt';` in `src/umap.js` fixes this, or at least appears to; I tested by publishing locally via `npm link` 🙃 

Here's the full diff between the Webpack builds:

```diff
diff --git a/dist/umap.js b/../react-dimensionality-reduction/node_modules/umap-js/dist/umap.js
index f8f1ae1..00b12b8 100644
--- a/dist/umap.js
+++ b/../react-dimensionality-reduction/node_modules/umap-js/dist/umap.js
@@ -60,13 +60,13 @@ var matrix = require("./matrix");
 var nnDescent = require("./nn_descent");
 var tree = require("./tree");
 var utils = require("./utils");
-var ml_levenberg_marquardt_1 = require("ml-levenberg-marquardt");
+var LM = require("ml-levenberg-marquardt");
 var SMOOTH_K_TOLERANCE = 1e-5;
 var MIN_K_DIST_SCALE = 1e-3;
 var UMAP = (function () {
     function UMAP(params) {
-        var _this = this;
         if (params === void 0) { params = {}; }
+        var _this = this;
         this.learningRate = 1.0;
         this.localConnectivity = 1.0;
         this.minDist = 0.1;
@@ -691,7 +691,7 @@ function findABParams(spread, minDist) {
         maxIterations: 100,
         errorTolerance: 10e-3,
     };
-    var parameterValues = ml_levenberg_marquardt_1.default(data, curve, options).parameterValues;
+    var parameterValues = LM(data, curve, options).parameterValues;
     var _a = __read(parameterValues, 2), a = _a[0], b = _a[1];
     return { a: a, b: b };
 }
```

### CODE REVIEW

**Comment by jebeck** [comment]
I signed it!

**Comment by cannoneyed** [comment]
Hey @jebeck! Thanks for submitting this PR - I'm having a bit of trouble reproducing the webpack issue myself, mind telling me a tiny bit more about your setup?

I tested the PR out and it seems like everything is working fine, so I'm inclined to merge it, though I'm always a bit worried that I don't actually understand `esModuleInterop` and `allowSyntheticDefaults` and all that :P

**Comment by jebeck** [comment]
Here's a [minimal example of the error](https://github.com/jebeck/umap-js-webpack-problem) via create-react-app (which actually isn't where I originally ran into it; I was using the Webpack build in [styleguidist](https://react-styleguidist.js.org/). Just clone, `npm i`, and then `npm start` and you'll see the error. (Node 10 for me today, was using 8 yesterday I think ¯\_(ツ)_/¯)

**Comment by cannoneyed** [comment]
Thanks for sending over this example! It's actually a bit strange - I can reproduce the error when installing from npm, but the error disappears when linking to the `master` branch locally... 

But your fix seems to work great, so I'm going to merge and then republish to npm.

Thanks!

**Comment by cannoneyed** [comment]
Also, just to follow up for posterity's sake - I goofed on npm publishing the library by adding a `publish` script to the package.json... running `npm publish` would both publish to npm and then call the script, then publish then call itself, leading to weird 1.1 builds on npm.... I can't believe it took me so long to figure this out :P - Anyway, 1.2 builds are legit on npm, hopefully this is all sorted!

Thanks again for the contrib

**Comment by jebeck** [comment]
Hey @cannoneyed, thanks so much! I was on vacay the last couple of weeks and just got back. Strangely, I'm getting the same error with v1.2.2 installed. I dove into the node_modules, and what I'm seeing in the build is unchanged.

Did you perhaps forget to make a fresh build in dist/ before publishing? 🤔

**Comment by jebeck** [comment]
OK, I went back to my fork, pulled from your master to my master and ran a build. I can no longer get the diff between bundles that I pasted above! (At first guess: because of that `esModuleInterop` flag, which I added *after* I pasted the diff.) So there's still something fishy going on, and I will dig in when I get time, which may not be very quickly, unfortunately.

It may also be that me using `npm link` to test my "fix" is/was not valid. I've run into this kind of thing before, unfortunately. The symlinks set up by `npm link` muddy the waters as far as getting imports from dependencies correct...

**Comment by jebeck** [comment]
Argh, nevermind 😅 

Things are working now. In my defense, my set up is complex: I'm working on a React library wrapping t-SNE and UMAP implementations, which has umap-js as a peerDependency, and then I have other demo apps that get our wrapper library and other dependencies linked in, and all my links between these things got in a weird state, so far as I can tell.

I updated that minimal example app that I put together to show the problem, and it works. And then I got everything else working, in the end...

**Pull request merged**
